# Generated by Django 5.2.7 on 2025-10-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_displayname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='displayname',
            field=models.CharField(default='n/a', max_length=50),
        ),
    ]
