# Generated by Django 5.2.7 on 2025-10-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profiletype',
            field=models.CharField(default='', max_length=10),
        ),
    ]
