# Generated by Django 5.2.7 on 2025-10-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profiletype',
            field=models.CharField(choices=[('PERSON', 'Person'), ('TRUCK', 'Truck'), ('STORE', 'Store')], max_length=30),
        ),
    ]
