# Generated by Django 5.2.7 on 2025-10-31 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_lapmonitorresult_deleted_lapmonitorresult_insertdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='human',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='races', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raceattribute',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='races.race'),
        ),
    ]
